source 'https://rubygems.org'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'capistrano', '2.15.5'
gem 'mongo'
gem 'bson_ext'
gem 'json'
gem 'mongo_mapper'
gem 'sinatra'
gem 'mustache'
gem 'i18n'
gem 'haml'
